#!/bin/sh
TIME=$(date +%s%N)
START=$TIME
RESET="\033[0m"

while IFS= read -r line; do
	printf "\r$RESET%7.7ss | \n" "$(echo "scale=3; ( $(date +%s%N) - $TIME ) / 1000000000" | bc)"
	TIME=$(date +%s%N)
	echo "         | $line\c"
done
printf "\r$RESET%7.7ss \n" "$(echo "scale=3; ( $(date +%s%N) - $TIME ) / 1000000000" | bc)"

echo
echo "Done in $(echo "scale=3; ( $(date +%s%N) - $START ) / 1000000000" | bc)s"
