#!/bin/bash

chord="${\"$1\"//#/%23/}"

wget -q -O - "https://scales-chords.com/chord/piano/$chord" \
| grep -o "http.*.jpg" | head -n 1 | xargs wget -q -O /tmp/chord.jpg \
|| echo "Chord not found" && exit 1

xdg-open /tmp/chord.jpg
