#!/bin/sh
DEVICE_ID=$(
	xinput --list \
		| sed '/Virtual core keyboard/,$ d; 1d; s/^\W*//' \
		| fzy \
		| grep -o 'id=\S*' \
		| cut -b 4-
)

CURRENT_SPEED=$(
	xinput --list-props $DEVICE_ID \
		| grep Matrix \
		| cut -d":" -f2 \
		| cut -d" " -f1
)

echo "Current Speed:${CURRENT_SPEED%?}"
read -p "New Speed: " speed

xinput --set-prop $DEVICE_ID "Coordinate Transformation Matrix" \
	$speed 0 0 0 $speed 0 0 0 1
