#!/bin/sh

[ -z "$DICTIONARY" ] \
	&& echo "Set DICTIONARY enviroment variable to a dictionary text file" \
	&& exit 1

( grep --color=always -i "^$*" "$DICTIONARY" ; grep --color=always -i "$*" "$DICTIONARY" ) | uniq | head -n 5
