#!/bin/sh

[ -z "$1" ] && PROMPT="> " || PROMPT="$1"

if [ -z "$2" ]; then
	cat | fzf "--prompt=$PROMPT" --no-info --reverse
else
	INDEX=`cat | nl -n ln | fzf "--prompt=$PROMPT" --with-nth 2 "-d	" --reverse --no-info | sed -E "s/\t.*//"`
	expr $INDEX - 1
fi

true
