#!/bin/sh

if [ -z "$FLASHCARD_FILE" ]; then
	echo 'Please set $FLASHCARD_FILE'
	exit 1
fi

if [ ! -z "$1" ]; then
	$EDITOR "$FLASHCARD_FILE"
	exit 0
fi

flash_card="$(sed 's/ |.*//' "$FLASHCARD_FILE" | fzy)"

grep "$flash_card" "$FLASHCARD_FILE" | sed "s/.*| //"
