#!/bin/sh

fontsize=`sudo showconsolefont -i | cut -dx -f2`

[ "$FONT_BOLD" = 1 ] && type="b" || type="n"
[ "$FONT_DUP" = 1 ] && duplicate="-d"

function prev() {
	echo -e "12\n14\n16\n18\n20\n22\n24\n28\n32" \
		| grep -B1 $fontsize | head -n1
}

function next() {
	echo -e "12\n14\n16\n18\n20\n22\n24\n28\n32" \
		| grep -A1 $fontsize | tail -n1
}

case "$1" in
	"")
		size=16;;
	min)
		size=12;;
	max)
		size=32;;
	+)
		size=`next`;;
	-)
		size=`prev`;;
	=)
		size="$fontsize";;
	*)
		size="$1";;
esac

sudo setfont "ter-9${size}${type}"  ${duplicate}
