#!/bin/sh

query=`echo $@ | tr " " "+"`
amount=15
threads=10

rm -rf /tmp/imgpreviews

wget --header="User-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11" "https://www.google.com/search?q=${query}&tbm=isch" -q -O - \
	| grep -B 1 '^,\["http' | grep -o 'http[^"]*' | tee /tmp/imgscript

sed -n 'p;n' /tmp/imgscript | sed 's/\\u003d/=/g;s/\\u0026/\&/g' \
	| head -n $amount | tee /tmp/imgpreviewlist | xargs -n 1 -P $threads \
	wget -qcP "/tmp/imgpreviews/"

sed -n 'n;p' /tmp/imgscript > /tmp/imgurls

selection=`sxiv -ot /tmp/imgpreviews/ | cut "--delimiter=/" -f4`

url=`grep "$selection" -n /tmp/imgpreviewlist | cut "-d:" -f1 \
	| xargs -I {} sed "{}q;d" /tmp/imgurls`

echo -e "$url"
