#!/bin/sh

DOING="work"
CICLES=0
CYCLE_END=`date +%s`
CURRENT_TIME=`date +%s`

#beep() {
#	aplay /dev/random -r 128000 -d 2 -q &
#}

display() {
	TIME_LEFT="$(expr $CYCLE_END - $CURRENT_TIME)"
	printf "\r$DOING $(date "-d@${TIME_LEFT}" -u +%M:%S)"
}

cycle() {
	CYCLE_END="$(date +%s --date="$1 minutes")"
	while [ "$CYCLE_END" -gt "$CURRENT_TIME" ]; do
		CURRENT_TIME=`date +%s`
		display
		sleep 1
	done
	beep
}

usage() {
	echo "POMODORO [mins...]"
	echo "Where mins is the amount of minutes in each cycle"
	echo "(alternating between work and rest)"
}

[ "$1" = "-h" ] || [ "$1" = "--help" ] && usage && exit 1

SEQUENCE="$([ -z "$*" ] && echo "25 5 25 5 25 35" || echo "$*")"

while true; do
	for TIME in $SEQUENCE; do
		cycle $TIME
		DOING=$([ "$DOING" = "rest" ] && echo work || echo rest)
	done
done
