#!/bin/bash

[ -z "$1" ] && THROWS=1 || THROWS="$1"

TOTAL=0

COLS=$(tput cols)

for (( i=0; i<$THROWS; i++)); do
	NUMBER=$(($RANDOM % 6 + 1))
	TOTAL=$((TOTAL + NUMBER))
	CURRENT_COLUMN=$((CURRENT_COLUMN + 6))

	[ "$CURRENT_COLUMN" -ge "$COLS" ] \
		&& echo -e "$ROW1\n$ROW2\n$ROW3\n$ROW4\n$ROW5" \
		&& ROW1="" && ROW2="" && ROW3="" && ROW4="" && ROW5="" && ROW6="" \
		&& CURRENT_COLUMN="6"

	case $NUMBER in
		1)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |   |"
			ROW3="${ROW3} | o |"
			ROW4="${ROW4} |   |"
			ROW5="${ROW5} -----";;
		2)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |o  |"
			ROW3="${ROW3} |   |"
			ROW4="${ROW4} |  o|"
			ROW5="${ROW5} -----";;
		3)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |o  |"
			ROW3="${ROW3} | o |"
			ROW4="${ROW4} |  o|"
			ROW5="${ROW5} -----";;
		4)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |o o|"
			ROW3="${ROW3} |   |"
			ROW4="${ROW4} |o o|"
			ROW5="${ROW5} -----";;
		5)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |o o|"
			ROW3="${ROW3} | o |"
			ROW4="${ROW4} |o o|"
			ROW5="${ROW5} -----";;
		6)
			ROW1="${ROW1} -----"
			ROW2="${ROW2} |o o|"
			ROW3="${ROW3} |o o|"
			ROW4="${ROW4} |o o|"
			ROW5="${ROW5} -----";;
	esac
done

echo -e "$ROW1\n$ROW2\n$ROW3\n$ROW4\n$ROW5"
echo "Total: $TOTAL"
