#!/bin/sh
[ -z "$1" ] && echo "Enter time in second or minute:second format" && exit 1

TIME=$(echo $1 | grep ":" >/dev/null \
	&& expr $(echo $1 | cut "-d:" -f1) "*" 60 + $(echo $1 | cut "-d:" -f2) \
	|| echo $1)

END=$(expr $(date +%s) + $TIME)

while true; do
	LEFT=$(expr $END - $(date +%s))
	[ "$LEFT" -lt 0 ] && exit
	printf "\r$(date "-d@${LEFT}" -u +%M:%S)"
	sleep 0.1
done
