#!/bin/sh
[ -z "$1" ] && echo "Usage: waitfor COMMAND" && exit 1

PID=$(pidof "$1")

[ -z "$PID" ] && echo "$1 is not running" && exit 1

while true; do
	sleep 2
	kill -0 "$PID" 2>/dev/null || exit 0
done
