#!/bin/bash

# Converts Windows Terminal themes to colorschemes usable by the "color" script.

source <(grep ":" "$1" | tr [:upper:] [:lower:] | sed -e s/\"//g -e "s/ //g" \
-e "s/:#/=/g" -e s/,//g -e s/purple/magenta/g -e /name:/d )

[ "$foreground" = "$black" ] && FG_COLOR="30"
[ "$foreground" = "$white" ] && FG_COLOR="37"
[ "$foreground" = "$red" ] && FG_COLOR="31"
[ "$foreground" = "$green" ] && FG_COLOR="32"
[ "$foreground" = "$blue" ] && FG_COLOR="34"
[ "$foreground" = "$yellow" ] && FG_COLOR="33"
[ "$foreground" = "$magenta" ] && FG_COLOR="35"
[ "$foreground" = "$cyan" ] && FG_COLOR="36"
[ "$foreground" = "$brightblack" ] && FG_COLOR="90"
[ "$foreground" = "$brightwhite" ] && FG_COLOR="97"
[ "$foreground" = "$brightred" ] && FG_COLOR="91"
[ "$foreground" = "$brightgreen" ] && FG_COLOR="92"
[ "$foreground" = "$brightblue" ] && FG_COLOR="94"
[ "$foreground" = "$brightyellow" ] && FG_COLOR="93"
[ "$foreground" = "$brightmagenta" ] && FG_COLOR="95"
[ "$foreground" = "$brightcyan" ] && FG_COLOR="96"

[ -z "$FG_COLOR" ] && white=$foreground && FG_COLOR="37"


[ "$background" = "$black" ] && BG_COLOR="40"
[ "$background" = "$white" ] && BG_COLOR="47"
[ "$background" = "$red" ] && BG_COLOR="41"
[ "$background" = "$green" ] && BG_COLOR="42"
[ "$background" = "$blue" ] && BG_COLOR="44"
[ "$background" = "$yellow" ] && BG_COLOR="43"
[ "$background" = "$magenta" ] && BG_COLOR="45"
[ "$background" = "$cyan" ] && BG_COLOR="46"
[ "$background" = "$brightblack" ] && BG_COLOR="100"
[ "$background" = "$brightwhite" ] && BG_COLOR="107"
[ "$background" = "$brightred" ] && BG_COLOR="101"
[ "$background" = "$brightgreen" ] && BG_COLOR="102"
[ "$background" = "$brightblue" ] && BG_COLOR="104"
[ "$background" = "$brightyellow" ] && BG_COLOR="103"
[ "$background" = "$brightmagenta" ] && BG_COLOR="105"
[ "$background" = "$brightcyan" ] && BG_COLOR="106"

[ -z "$BG_COLOR" ] && black=$background && BG_COLOR="40"


echo "echo -e '\033[${FG_COLOR};${BG_COLOR}m'"

echo ""
echo "black=$black"
echo "white=$white"
echo "red=$red"
echo "green=$green"
echo "blue=$blue"
echo "yellow=$yellow"
echo "magenta=$magenta"
echo "cyan=$cyan"
echo "brightblack=$brightblack"
echo "brightwhite=$brightwhite"
echo "brightred=$brightred"
echo "brightgreen=$brightgreen"
echo "brightblue=$brightblue"
echo "brightyellow=$brightyellow"
echo "brightmagenta=$brightmagenta"
echo "brightcyan=$brightcyan"
