#!/bin/sh

# Converts Windows Terminal themes to colorschemes usable by the "color" script.

grep -Ei "black|blue|cyan|green|purple|red|white|yellow|background" $1 \
| tr [:upper:] [:lower:] | sed -e s/\"//g -e "s/ //g" -e s/:#/=/g -e s/,//g    \
-e s/purple/magenta/g -e /black=/d -e s/background/black/g
