#!/bin/bash

[ -z $YT_DIR ] && echo "Please set env YT_DIR" && exit 1

[ -z $YT_DL ] && \
	YT_DL='nohup youtube-dl -f "best[height<=720]" {} -qo ' &&
	YT_DL+='"$YT_DIR/%(uploader)s - %(title)s.%(ext)s" >/dev/null 2>&1 &'

[ -z $YT_WATCH] && YT_WATCH='mpv "--ytdl-format=[height<=720]" {}'

IFS='\n'

index=1
rows="$(tput lines)"
cols="$(tput cols)"

BREAK="false"

while [ "$BREAK" = "false" ]; do
	echo "previous page" > /tmp/yt
	sed -n "$index,$((index + rows - 5))p" "$YT_DIR/videos" \
		| sed -e "s/|http.*$//" -e "s/^[0-9]*|//" \
		-e "s/&quot;/\"/g" -e "s/amp;//g" \
		| column -tO 2,1 -s "|" -T 0,1,2 -W 0,1,2 -c $cols \
		| tee /tmp/YT >> /tmp/yt
	echo -e "next page\nrefresh videos" >> /tmp/yt
	video=`</tmp/yt fzy -l max -p "Page $(((index+rows+30)/rows)): "`
	selection=`grep -n "$video" /tmp/yt | cut -d ":" -f 1`
	selection=`expr $selection - 1`

	case "$selection" in
		"0")
			index=$((index-rows-5<1?1:index-rows-4))
			;;
		"$((rows-3))")
			index=$((index+rows-4))
			;;
		"$((rows-2))")
			echo "refreshing..."
			ytdl
			index=1
			;;
		"")
			BREAK="true"
			;;
		*)
			selection=$((selection+index))
			sed -e "$((selection-1))s/[^|]*|[^|]*|/\0(W) /" \
				-e "$((selection-1))s/(W) (W) /(W) /" -i "$YT_DIR/videos"
			url="$(sed -n "$((selection-1))p" "$YT_DIR/videos" | cut "-d|" -f4)"
		
			echo "Watch now? (n)"
			read answer

			[ "$answer" = "y" ] && eval "${YT_WATCH//\{\}/$url}"
			[ "$answer" != "y" ] && eval "${YT_DL//\{\}/$url}"
			;;
	esac
done
