#!/bin/sh

amount=15

[ -z "$1" ] && echo "Please enter query" && exit 1

query=`echo $@ | sed -Ee 's/ /+/g' -e 's/-//g'`

wget --header="User-Agent: Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11" \
	"https://youtube.com/results?search_query=$query" -q -O - \
	> /tmp/ytsearch

grep -Eo '"title":{"runs":\[{"text":"[^"]*' /tmp/ytsearch \
	| sed 's/"title":{"runs":\[{"text":"//' | head -n $amount > /tmp/ytsearchtitles

grep -Eo 'v=[^"]*' /tmp/ytsearch | tail -n +3 | head -n $amount \
	| sed 's|^|https://youtube.com/watch?|' | paste -d "|" /tmp/ytsearchtitles - \
	| column -t -s "|"
