#!/bin/bash

TH=8 # Threads

[ -z "$YT_FILE" ] && echo "Please set env YT_FILE" && exit 1
[ -z "$YT_DIR" ] && echo "Please set env YT_DIR" && exit 1

grep -o 'http[^"]*' "$YT_FILE" | xargs -n 1 -P $TH wget -q -c -P "$YT_DIR/xml/"

output=""

[ -f "$YT_DIR/last_update" ] \
	&& last_update=$(cat "$YT_DIR/last_update") \
	|| last_update=0

date "+%s" > $YT_DIR/last_update

for file in $YT_DIR/xml/*; do
	IFS=$'\n' titles=($(pcregrep -o1 "<title>(.*)<\/title>" "$file"))
	dates=($(pcregrep -o1 "<published>(.*)<\/published>" "$file"))
	links=($(pcregrep -o1 "rel=\"alternate\" href=\"(.*)\"" "$file"))
	videos=${#titles[@]}
	channel=${titles[0]//|/-}
	for (( i=1; i<$videos; i++)); do
		timestamp=$(date --date="${dates[$i]}" +%s)
		title=${titles[$i]//|/-}
		link=${links[$i]}
		[ "$timestamp" -gt "$last_update" ] \
			&& output+="$timestamp|$channel|$title|$link\n"
	done
done

cat <(echo -e "$output\c" | sort -r ; cat "$YT_DIR/videos") > /tmp/ytdl
rm "$YT_DIR/videos"
cp /tmp/ytdl "$YT_DIR/videos"
