#!/bin/bash

[ -z $YT_DIR ] && echo "Please set env YT_DIR" && exit 1

[ -z $YT_OFF ] && YT_OFF='mpv "{}"'
[ -z $YT_RM ] && YT_RM='rm "{}"'

index=1
rows="$(tput lines)"
cols="$(tput cols)"

BREAK="false"

while [ "$BREAK" = "false" ]; do
	echo -e "previous page\nnext page" > /tmp/mmenu
	find "$YT_DIR" -maxdepth 1 -name "*.*" -printf "%f\n" \
		| sed -n "$index,$((index+rows-5))p" >> /tmp/mmenu
	mmenu "Page $(((index+rows+30)/rows)): " && selection="$(cat /tmp/mmenu)"

	case "$selection" in
		"previous page")
			index=$((index-rows-4<1?1:index-rows-4))
			;;
		"next page")
			index=$((index+rows-4))
			;;
		"")
			BREAK="true"
			;;
		*)
			file="$YT_DIR/$selection"
			echo "w(atch) or r(emove)? (w)"
			read answer
			[ "$answer" = "r" ] && eval "${YT_RM//\{\}/$file}"
			[ "$answer" != "r" ] && eval "${YT_OFF//\{\}/$file}"
			;;
	esac
done
